services:
    _defaults:
        autowire:       true
        autoconfigure:  true

    ########################################################################
    # Auto-wire for Metadata Collectors
    Splash\Metadata\Collectors\:
      resource:     "../../Collectors"

    ########################################################################
    # Auto-wire for Field Data Transformers
    Splash\Metadata\DataTransformer\:
        resource:     "../../DataTransformer"

    ########################################################################
    # Auto-wire for Services
    Splash\Metadata\Services\:
        resource: "../../Services"